name: "Andre"
description: "Warden of the Code Clean"

google_analytics:

url: https://andxpto.github.io
baseurl: ""

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME