# Permalinks
permalink: pretty

# Thanks to Bradley Taunt (https://github.com/bradleytaunt/lightspeed)
#
# Setup
title: "andxpto"
url: https://andxpto.github.io
tagline: "warden of the XPTO"
baseurl: ""



# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

 exclude:
  - Gemfile
  - LICENSE
  - README.md
  - CNAME
