name: "Andre"
description: "Warden of the Code Clean"
author: andxpto
email: andrecorreiait@gmail.com

social_links:
    twitter: andxpto
    github: andxpto
    linkedin: andcorreia

sass:
    style: :compressed
    sass_dir: assets/css/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME