# Permalinks
permalink: pretty

# Thanks to Bradley Taunt (https://github.com/bradleytaunt/lightspeed)
#
# Setup
title: "xnzz"
url: https://xndry.github.io
tagline: "x os n cs z pt z"
baseurl: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - CNAME
