name: "Andre"
description: "Warden of the Code Clean"
author: andxpto
email: andrecorreiait@gmail.com

url: https://andxpto.github.io
baseurl: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME